name: 3. Minimal Log Failure (Exit Code) Demo

on:
  workflow_dispatch:

jobs:
  minimal_log_failure_demo:
    name: 🤫 Exit Code Failure Test
    runs-on: ubuntu-latest
    steps:
      - name: Suppress error log and fail with exit code
        run: |
          echo "Testing intentional failure without verbose logging..."
          
          # 존재하지 않는 명령어를 호출하여 에러를 발생시키지만,
          # 2> /dev/null 명령어로 표준 에러(stderr)를 무시(로그 삭제)합니다.
          ls /definitely-not-here 2> /dev/null
          
          # 의도적으로 1이라는 종료 코드를 반환하여 Job을 실패시킵니다.
          exit 1
