name: 2. Timeout Failure Demo

on:
  workflow_dispatch:

jobs:
  timeout_failure_demo:
    name: ⏱️ Timeout Test (1 Minute)
    runs-on: ubuntu-latest
    # Job 전체 타임아웃을 1분(60초)으로 설정
    timeout-minutes: 1 
    steps:
      - name: Sleep longer than timeout
        run: |
          echo "Starting a 120 second process..."
          # 1분 타임아웃을 초과하는 2분 동안 대기합니다.
          sleep 120s
          echo "Process finished (This line should NOT be reached and will be cancelled)."
