name: Code Error Tracking Test
on: [push, workflow_dispatch]

jobs:
  code_error_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run buggy TypeScript (should fail)
        run: npx -y ts-node src/test/buggyModule.ts
